/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/circles/{circle_id}/meetings/{meeting_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Action */
        post: operations["record_action_circles__circle_id__meetings__meeting_id__actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/{action_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Report Action */
        patch: operations["report_action_actions__action_id__patch"];
        trace?: never;
    };
    "/members/{member_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Member History */
        get: operations["member_history_members__member_id__actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/circles/{circle_id}/meetings/next/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Next Check In
         * @description `as_of` fixes the clock for demos and tests. Defaults to now.
         */
        get: operations["next_check_in_circles__circle_id__meetings_next_check_in_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionResponse */
        ActionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Meeting Id
             * Format: uuid
             */
            meeting_id: string;
            /**
             * Member Id
             * Format: uuid
             */
            member_id: string;
            /**
             * Circle Id
             * Format: uuid
             */
            circle_id: string;
            /** Text */
            text: string;
            /** Why */
            why: string | null;
            status: components["schemas"]["ActionStatus"];
            /** Note */
            note: string | null;
            /** Created At */
            created_at: string | null;
        };
        /**
         * ActionStatus
         * @enum {string}
         */
        ActionStatus: "committed" | "done" | "partly" | "not_yet";
        /** CheckInActionOut */
        CheckInActionOut: {
            member: components["schemas"]["MemberOut"];
            /** Text */
            text: string;
            status: components["schemas"]["ActionStatus"];
            /** Note */
            note: string | null;
            committed_at: components["schemas"]["MeetingRefOut"];
            /** Carried Over */
            carried_over: boolean;
        };
        /** CheckInResponse */
        CheckInResponse: {
            circle: components["schemas"]["CircleOut"];
            next_meeting: components["schemas"]["NextMeetingOut"];
            since_meeting: components["schemas"]["MeetingRefOut"] | null;
            /** Actions */
            actions: components["schemas"]["CheckInActionOut"][];
            follow_through: components["schemas"]["FollowThroughOut"];
            /** Opener */
            opener: string;
            /** Opener Source */
            opener_source: string;
        };
        /** CircleOut */
        CircleOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** FollowThroughOut */
        FollowThroughOut: {
            /** Window Meetings */
            window_meetings: number;
            /** Committed */
            committed: number;
            /** Done */
            done: number;
            /** Partly */
            partly: number;
            /** Not Yet */
            not_yet: number;
            /** Open */
            open: number;
            /** Rate */
            rate: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MeetingRefOut */
        MeetingRefOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Held At
             * Format: date-time
             */
            held_at: string;
        };
        /** MemberOut */
        MemberOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Name */
            display_name: string;
        };
        /** NextMeetingOut */
        NextMeetingOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Held At
             * Format: date-time
             */
            held_at: string;
            moderator: components["schemas"]["MemberOut"] | null;
        };
        /** RecordActionRequest */
        RecordActionRequest: {
            /** Text */
            text: string;
            /** Why */
            why?: string | null;
        };
        /** ReportActionRequest */
        ReportActionRequest: {
            status: components["schemas"]["ActionStatus"];
            /** Note */
            note?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    record_action_circles__circle_id__meetings__meeting_id__actions_post: {
        parameters: {
            query?: never;
            header: {
                "x-member-id": string;
            };
            path: {
                circle_id: string;
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_action_actions__action_id__patch: {
        parameters: {
            query?: never;
            header: {
                "x-member-id": string;
            };
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    member_history_members__member_id__actions_get: {
        parameters: {
            query?: never;
            header: {
                "x-member-id": string;
            };
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    next_check_in_circles__circle_id__meetings_next_check_in_get: {
        parameters: {
            query?: {
                window?: number;
                as_of?: string | null;
            };
            header: {
                "x-member-id": string;
            };
            path: {
                circle_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
